// <auto-generated />
using CSharpModelTrainerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpModelTrainerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315203651_AddedWeightedAverageToLungCancerModel")]
    partial class AddedWeightedAverageToLungCancerModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("SharedCL.LungCancerPrediction.Models.LungCancerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BenignF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("BenignPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("BenignRecall")
                        .HasColumnType("REAL");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MacroF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("MacroPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("MacroRecall")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantRecall")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("NormalF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("NormalPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("NormalRecall")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValidationAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValidationLoss")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedRecall")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LungCancerModels");
                });

            modelBuilder.Entity("SharedCL.SentimentAnalysis.Models.SentimentAnalysisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TestingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingAreaUnderRocCurve")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingPositivePrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingPositiveRecall")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainerAlgorithm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TrainingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingAreaUnderRocCurve")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingPositivePrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingPositiveRecall")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SentimentAnalysisModels");
                });
#pragma warning restore 612, 618
        }
    }
}
