// <auto-generated />
using CSharpModelTrainerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpModelTrainerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529073426_AddedMoreTimeStats")]
    partial class AddedMoreTimeStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CSharpModelTrainerApi.LungCancerPrediction.Models.LCEpochData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BenignF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("BenignPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("BenignRecall")
                        .HasColumnType("REAL");

                    b.Property<int>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LCModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MacroF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("MacroPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("MacroRecall")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("MalignantRecall")
                        .HasColumnType("REAL");

                    b.Property<double?>("NormalF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("NormalPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("NormalRecall")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingLoss")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValidationAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValidationLoss")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedPrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedRecall")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LCModelId");

                    b.ToTable("LCEpochData");
                });

            modelBuilder.Entity("CSharpModelTrainerApi.LungCancerPrediction.Models.LCModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataLoadingTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidationTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LCModels");
                });

            modelBuilder.Entity("CSharpModelTrainerApi.LungCancerPrediction.Models.LCEpochData", b =>
                {
                    b.HasOne("CSharpModelTrainerApi.LungCancerPrediction.Models.LCModel", "LCModel")
                        .WithMany("EpochData")
                        .HasForeignKey("LCModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LCModel");
                });

            modelBuilder.Entity("CSharpModelTrainerApi.LungCancerPrediction.Models.LCModel", b =>
                {
                    b.Navigation("EpochData");
                });
#pragma warning restore 612, 618
        }
    }
}
