// <auto-generated />
using CSharpModelTrainerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpModelTrainerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309143837_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("SharedCL.SentimentAnalysis.Models.SentimentAnalysisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TestingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingAreaUnderRocCurve")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingPositivePrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestingPositiveRecall")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainerAlgorithm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TrainingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingAreaUnderRocCurve")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingF1Score")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingPositivePrecision")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrainingPositiveRecall")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SentimentAnalysisModels");
                });
#pragma warning restore 612, 618
        }
    }
}
