using System.Globalization;

namespace WebApp;

public static class Loc
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["en-US"] = new()
        {
            ["LCHome_Title"] = "Lung Cancer Analysis",
            ["LCHome_Description"] = "This platform is used for training, analyzing, and directly comparing machine learning models developed in C# and Python programming languages ​​using IQOTHNCCD CT diagnostics.",
            ["LCHome_TrainModel"] = "Train Model",
            ["LCHome_TrainModelDescription" ] = "Configure and start the training process of a new model. Set the number of epochs, image augmentation (rotation), and select the desired backend system (C# or Python).",
            ["LCHome_TrainModelAction"] = "Start Training",
            ["LCHome_RunAnalysis"] = "Run Analysis",
            ["LCHome_RunAnalysisDescription"] = "Evaluate the trained models on independent CT scans of the lungs. The model will classify the tissue as normal, benign, or malignant.",
            ["LCHome_RunAnalysisAction"] = "New Analysis",
            ["LCHome_ReviewModels"] = "Review Models",
            ["LCHome_ReviewModelsDescription"] = "View the history of all models trained so far, analyze their final parameters, or delete those that are no longer needed.",
            ["LCHome_ReviewModelsAction"] = "Open Overview",
            ["LCHome_Comparison"] = "Compare Models",
            ["LCHome_ComparisonDescription"] = "Directly compare the performance of different models across epochs (Loss, Accuracy). Select any number of models to generate graphs.",
            ["LCHome_ComparisonAction"] = "Compare Performance",

            ["LCTrainer_PageTitle"] = "Lung Cancer Model Training",
            ["LCTrainer_Title"] = "Model Training",
            ["LCTrainer_NameRequired"] = "Model name is required.",
            ["LCTrainer_ModelName"] = "Model Name",
            ["LCTrainer_EpochsRequired"] = "Number of epochs is required.",
            ["LCTrainer_Epochs"] = "Epochs",
            ["LCTrainer_ModelLanguageRequired"] = "Model language is required.",
            ["LCTrainer_ModelLanguage"] = "Model Language",
            ["LCTrainer_WithFlips"] = "Rotate images (Augmentation)",
            ["LCTrainer_ShowResults"] = "Show Results",
            ["LCTrainer_LoadingText"] = "Training...",
            ["LCTrainer_Train"] = "Train",
            ["LCTrainer_InitModelName"] = "LungCancerModel",
            ["LCTrainer_TrainingError"] = "An error occurred during model training. Please try again.",
            ["LCTrainer_SavingError"] = "The model was trained, but an error occurred while saving the model. Please try again.",
            ["LCTrainer_TrainingSuccess"] = "The model was successfully trained and saved.",

            ["LCInfo_Title"] = "Model Details",
            ["LCInfo_Epochs"] = "Epochs",
            ["LCInfo_Seconds"] = "Seconds",
            ["LCInfo_Performance"] = "Performance",
            ["LCInfo_Metric"] = "Metric",
            ["LCInfo_Training"] = "Training",
            ["LCInfo_Validation"] = "Validation",
            ["LCInfo_Accuracy"] = "Accuracy",
            ["LCInfo_Loss"] = "Loss",
            ["LCInfo_Recall"] = "Recall",
            ["LCInfo_PerformanceTimes"] = "Performance Times",
            ["LCInfo_Step"] = "Step",
            ["LCInfo_TimeSeconds"] = "Time in Seconds",
            ["LCInfo_DataLoading"] = "Data Loading",
            ["LCInfo_TrainingTime"] = "Training Time",
            ["LCInfo_ValidationTime"] = "Validation Time",
            ["LCInfo_TotalTime"] = "Total Time",
            ["LCInfo_Seconds"] = "seconds",
            ["LCInfo_PerformanceByClass"] = "Performance by Class",
            ["LCInfo_ClassByClass"] = "Class",
            ["LCInfo_RecallByClass"] = "Recall",
            ["LCInfo_PrecisionByClass"] = "Precision",
            ["LCInfo_F1ScoreByClass"] = "F1 Score",
            ["LCInfo_MacroAverage"] = "Macro Average",
            ["LCInfo_NormalClass"] = "Normal",
            ["LCInfo_BenignClass"] = "Benign",
            ["LCInfo_MalignantClass"] = "Malignant",
            ["LCInfo_Error"] = "Error occurred while loading model details. Please try again.",

            ["LCInference_PageTitle"] = "Image Analysis",
            ["LCInference_Title"] = "Image Analysis",
            ["LCInference_Description"] = "Select a CT scan of the lungs",
            ["LCInference_ImageRequired"] = "Image is required!",
            ["LCInference_BrowseFiles"] = "Browse Files",
            ["LCInference_ChangeImage"] = "Change Image",
            ["LCInference_ModelSelect"] = "Model for Analysis",
            ["LCInference_ModelRequired"] = "Model is required!",
            ["LCInference_Result"] = "Result: ",
            ["LCInference_PredictionTime"] = "seconds",
            ["LCInference_LoadingText"] = "Analyzing...",
            ["LCInference_AnalyzeImage"] = "Analyze Image",
            ["LCInference_ModelLoadingError"] = "Error occurred while loading the models. Please try again.",
            ["LCInference_AnalysisError"] = "Error occurred while analyzing the image. Please try again.",
            ["LCInference_FileSizeError"] = "File size is too large! (over 5MB). Please try again.",

            ["LCModels_PageTitle"] = "Models Overview",
            ["LCModels_Title"] = "Models Overview",
            ["LCModels_Search"] = "Search models...",
            ["LCModels_NoResults"] = "Models not found",
            ["LCModels_ChangeFilters"] = "Change filters to display models",
            ["LCModels_NoModels"] = "Train your first model to get started with analysis",
            ["LCModels_Name"] = "Name",
            ["LCModels_Language"] = "Language",
            ["LCModels_Recall"] = "Recall",
            ["LCModels_Precision"] = "Precision",
            ["LCModels_F1Score"] = "F1 Score",
            ["LCModels_Details"] = "Details",
            ["LCModels_Delete"] = "Delete",
            ["LCModels_Error"] = "Error occurred while loading the model. Please try again.",
            ["LCModels_ConfirmDelete"] = "Are you sure you want to delete the model?",
            ["LCModels_DeleteError"] = "Error occurred while deleting the model. Please try again.",
            ["LCModels_DeleteSuccess"] = "Model deleted successfully.",


            ["LCComparison_PageTitle"] = "Model Comparison",
            ["LCComparison_Title"] = "Model Comparison",
            ["LCComparison_NoModels"] = "No available models for comparison.",
            ["LCComparison_ModelSelect"] = "Select Models",
            ["LCComparison_MetricSelect"] = "Select Metrics",
            ["LCComparison_NoMetricsSelected"] = "Select at least one metric to display the chart.",
            ["LCComparison_LoadModelsError"] = "Error occurred while loading models. Please try again.",
            ["LCComparison_MacroPrecision"] = "Macro Precision",
            ["LCComparison_MacroRecall"] = "Macro Recall",
            ["LCComparison_MacroF1Score"] = "Macro F1 Score",
            ["LCComparison_TrainingLoss"] = "Training Loss",
            ["LCComparison_TrainingPrecision"] = "Training Precision",
            ["LCComparison_ValidationLoss"] = "Validation Loss",
            ["LCComparison_ValidationPrecision"] = "Validation Precision",
            ["LCComparison_BenignPrecision"] = "Precision (Benign)",
            ["LCComparison_BenignRecall"] = "Recall (Benign)",
            ["LCComparison_BenignF1Score"] = "F1 (Benign)",
            ["LCComparison_MalignantPrecision"] = "Precision (Malignant)",
            ["LCComparison_MalignantRecall"] = "Recall (Malignant)",
            ["LCComparison_MalignantF1Score"] = "F1 (Malignant)",
            ["LCComparison_NormalPrecision"] = "Precision (Normal)",
            ["LCComparison_NormalRecall"] = "Recall (Normal)",
            ["LCComparison_NormalF1Score"] = "F1 (Normal)",

            ["LCLayout_Title"] = "Lung Cancer Analysis",
            ["LCLayout_English"] = "English",
            ["LCLayout_Bosnian"] = "Bosnian",

            ["LCErrors_UnauthorizedAccess"] = "Unauthorized access.",
            ["LCErrors_ErrorFetchingData"] = "Error occurred while fetching data. Please try again.",
            ["LCErrors_ErrorGeneric"] = "An unexpected error occurred. Please try again."
        },
        ["bs-BA"] = new()
        {
            ["LCHome_Title"] = "Analiza raka pluća",
            ["LCHome_Description"] = "Ova platforma služi za treniranje, analizu i direktnu usporedbu modela mašinskog učenja razvijenih u C# i Python programskim jezicima koristeći IQOTHNCCD CT dijagnostiku.",
            ["LCHome_TrainModel"] = "Treniraj model",
            ["LCHome_TrainModelDescription"] = "Konfigurišite i pokrenite proces treniranja novog modela. Podesite broj epoha, augmentaciju slika (rotaciju) i odaberite željeni backend sistem (C# ili Python).",
            ["LCHome_TrainModelAction"] = "Započni Treniranje",
            ["LCHome_RunAnalysis"] = "Pokreni Analizu",
            ["LCHome_RunAnalysisDescription"] = "Izvršite evaluaciju istreniranih modela na nezavisnim CT snimcima pluća. Model će klasifikovati tkivo kao normalno, benigno ili maligno.",
            ["LCHome_RunAnalysisAction"] = "Nova Analiza",
            ["LCHome_ReviewModels"] = "Pregled modela",
            ["LCHome_ReviewModelsDescription"] = "Pregledajte historiju svih do sada treniranih modela, analizirajte njihove finalne parametre ili obrišite one koji više nisu potrebni.",
            ["LCHome_ReviewModelsAction"] = "Otvori Pregled",
            ["LCHome_Comparison"] = "Uporedi Modele",
            ["LCHome_ComparisonDescription"] = "Direktno usporedite performanse različitih modela kroz epohe (Loss, Accuracy). Odaberite proizvoljan broj modela za generisanje grafikona.",
            ["LCHome_ComparisonAction"] = "Uporedi Performanse",

            ["LCTrainer_PageTitle"] = "Treniranje Modela za Rak Pluća",
            ["LCTrainer_Title"] = "Treniranje Modela",
            ["LCTrainer_NameRequired"] = "Naziv modela je obavezan.",
            ["LCTrainer_ModelName"] = "Naziv Modela",
            ["LCTrainer_EpochsRequired"] = "Broj epoha je obavezan.",
            ["LCTrainer_Epochs"] = "Epohe",
            ["LCTrainer_ModelLanguageRequired"] = "Jezik modela je obavezan.",
            ["LCTrainer_ModelLanguage"] = "Jezik Modela",
            ["LCTrainer_WithFlips"] = "Rotiraj slike (Augmentacija)",
            ["LCTrainer_ShowResults"] = "Prikaži Rezultate",
            ["LCTrainer_LoadingText"] = "Treniranje...",
            ["LCTrainer_Train"] = "Treniraj",
            ["LCTrainer_InitModelName"] = "ModelZaRakPluca",
            ["LCTrainer_TrainingError"] = "Došlo je do greške tokom treniranja modela. Molimo pokušajte ponovo.",
            ["LCTrainer_SavingError"] = "Model je treniran, ali došlo je do greške prilikom spremanja modela. Molimo pokušajte ponovo.",
            ["LCTrainer_TrainingSuccess"] = "Model je uspješno treniran i spremljen.",

            ["LCInfo_Title"] = "Detalji Modela",
            ["LCInfo_Epochs"] = "Epoha",
            ["LCInfo_Seconds"] = "Sekundi",
            ["LCInfo_Performance"] = "Performanse",
            ["LCInfo_Metric"] = "Metrika",
            ["LCInfo_Training"] = "Trening",
            ["LCInfo_Validation"] = "Validacija",
            ["LCInfo_Accuracy"] = "Preciznost",
            ["LCInfo_Loss"] = " Gubitak (Loss)",
            ["LCInfo_Recall"] = "Odziv",
            ["LCInfo_PerformanceTimes"] = "Vremenske Oznake",
            ["LCInfo_Step"] = "Korak",
            ["LCInfo_TimeSeconds"] = "Vrijeme u Sekundama",
            ["LCInfo_DataLoading"] = "Učitavanje Podataka",
            ["LCInfo_TrainingTime"] = "Vrijeme Treniranja",
            ["LCInfo_ValidationTime"] = "Vrijeme Validacije",
            ["LCInfo_TotalTime"] = "Ukupno Vrijeme",
            ["LCInfo_Seconds"] = "sekundi",
            ["LCInfo_PerformanceByClass"] = "Detalji po klasama",
            ["LCInfo_ClassByClass"] = "Klasa",
            ["LCInfo_RecallByClass"] = "Odziv (Recall)",
            ["LCInfo_PrecisionByClass"] = "Preciznost",
            ["LCInfo_F1ScoreByClass"] = "F1 Score",
            ["LCInfo_MacroAverage"] = "Makro Prosjek",
            ["LCInfo_NormalClass"] = "Normalno",
            ["LCInfo_BenignClass"] = "Benigno",
            ["LCInfo_MalignantClass"] = "Maligno",
            ["LCInfo_Error"] = "Greška prlikom učitavanja detalja modela. Molimo pokušajte ponovo.",

            ["LCInference_PageTitle"] = "Analiza Slike",
            ["LCInference_Title"] = "Analiza Slike",
            ["LCInference_Description"] = "Odaberite CT snimak pluća",
            ["LCInference_ImageRequired"] = "Slika je obavezna!",
            ["LCInference_BrowseFiles"] = "Pretraži fajlove",
            ["LCInference_ChangeImage"] = "Promijeni sliku",
            ["LCInference_ModelSelect"] = "Model za analizu",
            ["LCInference_ModelRequired"] = "Model je obavezan!",
            ["LCInference_Result"] = "Rezultat",
            ["LCInference_PredictionTime"] = "sekundi",
            ["LCInference_LoadingText"] = "Analiziranje...",
            ["LCInference_AnalyzeImage"] = "Analiziraj Sliku",
            ["LCInference_ModelLoadingError"] = "Greška prilikom učitavanja modela. Molimo pokušajte ponovo.",
            ["LCInference_AnalysisError"] = "Greška prilikom analiziranja. Molimo pokušajte ponovo.",
            ["LCInference_FileSizeError"] = "Veličina fajla prevelika! (preko 5MB). Molimo pokušajte ponovo.",

            ["LCModels_PageTitle"] = "Pregled Modela",
            ["LCModels_Title"] = "Pregled Modela",
            ["LCModels_Search"] = "Pretraži modele...",
            ["LCModels_NoResults"] = "Modeli nisu pronađeni",
            ["LCModels_ChangeFilters"] = "Promjenite filtere za prikaz modela",
            ["LCModels_NoModels"] = "Trenirajte prvi model da možete početi raditi analizu",
            ["LCModels_Name"] = "Naziv",
            ["LCModels_Language"] = "Jezik",
            ["LCModels_Recall"] = "Odziv",
            ["LCModels_Precision"] = "Preciznost",
            ["LCModels_F1Score"] = "F1 Score",
            ["LCModels_Details"] = "Detalji",
            ["LCModels_Delete"] = "Obriši",
            ["LCModels_Error"] = "Greška prilikom učitavanja modela. Molimo pokušajte ponovo.",
            ["LCModels_ConfirmDelete"] = "Da li ste sigurni da želite obrisati model?",
            ["LCModels_DeleteError"] = "Greška pri brisanju modela. Molimo pokušajte ponovo.",
            ["LCModels_DeleteSuccess"] = "Model je uspješno obrisan.",

            ["LCComparison_PageTitle"] = "Usporedba Modela",
            ["LCComparison_Title"] = "Usporedba Modela",
            ["LCComparison_NoModels"] = "Nema dostupnih modela za poređenje.",
            ["LCComparison_ModelSelect"] = "Odaberite Modele",
            ["LCComparison_MetricSelect"] = "Odaberite Metrike",
            ["LCComparison_NoMetricsSelected"] = "Odaberite barem jednu metriku za prikaz grafikona.",
            ["LCComparison_LoadModelsError"] = "Greška prilikom učitavanja modela. Molimo pokušajte ponovo.",
            ["LCComparison_MacroPrecision"] = "Makro preciznost",
            ["LCComparison_MacroRecall"] = "Makro odziv",
            ["LCComparison_MacroF1Score"] = "Makro F1 Score",
            ["LCComparison_TrainingLoss"] = "Gubitak pri treniranju",
            ["LCComparison_TrainingPrecision"] = "Preciznost pri treniranju",
            ["LCComparison_ValidationLoss"] = "Gubitak pri validaciji",
            ["LCComparison_ValidationPrecision"] = "Preciznost pri validaciji",
            ["LCComparison_BenignPrecision"] = "Preciznost (Benigno)",
            ["LCComparison_BenignRecall"] = "Odziv (Benigno)",
            ["LCComparison_BenignF1Score"] = "F1 (Benigno)",
            ["LCComparison_MalignantPrecision"] = "Preciznost (Maligno)",
            ["LCComparison_MalignantRecall"] = "Odziv (Maligno)",
            ["LCComparison_MalignantF1Score"] = "F1 (Maligno)",
            ["LCComparison_NormalPrecision"] = "Preciznost (Normalno)",
            ["LCComparison_NormalRecall"] = "Odziv (Normalno)",
            ["LCComparison_NormalF1Score"] = "F1 (Normalno)",

            ["LCLayout_Title"] = "Analiza Raka Pluća",
            ["LCLayout_English"] = "Engleski",
            ["LCLayout_Bosnian"] = "Bosanski",

            ["LCErrors_UnauthorizedAccess"] = "Pristup nije dozvoljen.",
            ["LCErrors_ErrorFetchingData"] = "Greška prilikom učitavanja podataka. Molimo pokušajte ponovo.",
            ["LCErrors_ErrorGeneric"] = "Greška prilikom obrade zahtjeva. Molimo pokušajte ponovo."


        }
    };

    public static string T(string key)
    {
        var currentCulture = CultureInfo.CurrentUICulture.Name;

        if (Translations.TryGetValue(currentCulture, out var localizedStrings) &&
            localizedStrings.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Translations["en-US"].TryGetValue(key, out var fallbackValue))
        {
            return fallbackValue;
        }

        return key;
    }
}